export const statNameMap: Record<string, string> = {
    hp: 'Health',
    hpperlevel: 'Health per Level',
    mp: 'Mana',
    mpperlevel: 'Mana per Level',
    movespeed: 'Move Speed',
    moveSpeed: 'Move Speed',
    armor: 'Armor',
    armorperlevel: 'Armor per Level',
    spellblock: 'Magic Resist',
    spellblockperlevel: 'Magic Resist per Level',
    attackrange: 'Attack Range',
    hpregen: 'Health Regen',
    hpregenperlevel: 'Health Regen per Level',
    mpregen: 'Mana Regen',
    mpregenperlevel: 'Mana Regen per Level',
    crit: 'Crit Chance',
    critperlevel: 'Crit Chance per Level',
    attackdamage: 'Attack Damage',
    attackdamageperlevel: 'Attack Damage per Level',
    attackspeedperlevel: 'Attack Speed per Level',
    attackspeed: 'Attack Speed',
  
    abilitypower: 'Ability Power',
    abilityhaste: 'Ability Haste',
    lethality: 'Lethality',
    armorpenetration: 'Armor Penetration',
    magicpenetration: 'Magic Penetration',
    omnivamp: 'Omnivamp',
    lifesteal: 'Life Steal',
    healandshieldpower: 'Heal & Shield Power',
    tenacity: 'Tenacity',
    cooldownreduction: 'Cooldown Reduction',
    goldper10: 'Gold per 10s',
    mana: 'Mana',
    health: 'Health',
  };
  