// export const statNameMap: Record<string, string> = {
  // FlatArmorMod: 'Armor',
  // FlatAttackDamageMod: 'Attack Damage',
  // FlatBlockMod: 'Block',
  // FlatCritChanceMod: 'Critical Strike Chance',
  // FlatCritDamageMod: 'Critical Strike Damage',
  // FlatEXPBonus: 'Bonus Experience',
  // FlatEnergyRegenMod: 'Energy Regen /5s',
  // FlatHPPoolMod: 'Health',
  // FlatHPRegenMod: 'Health Regen /5s',
  // FlatLethalityMod: 'Lethality',
  // FlatMagicDamageMod: 'Magic Damage',
  // FlatMagicPenMod: 'Magic Penetration',
  // FlatManaPoolMod: 'Mana',
  // FlatManaRegenMod: 'Mana Regen /5s',
  // FlatMovementSpeedMod: 'Movement Speed',
  // FlatPhysicalDamageMod: 'Bonus Physical Damage',
  // FlatSpellBlockMod: 'Magic Resist',
  // FlatSpellVampMod: 'Spell Vamp',
  // FlatTimeDeadMod: 'Time Dead',
  // FlatGoldPer10Mod: 'Gold per 10 Seconds',

  // PercentArmorMod: 'Armor %',
  // PercentAttackDamageMod: 'Attack Damage %',
  // PercentBlockMod: 'Block %',
  // PercentCritChanceMod: 'Critical Strike Chance %',
  // PercentCritDamageMod: 'Critical Strike Damage %',
  // PercentEXPBonus: 'Bonus Experience %',
  // PercentHPPoolMod: 'Health %',
  // PercentHPRegenMod: 'Health Regen %',
  // PercentLifeStealMod: 'Life Steal %',
  // PercentMagicDamageMod: 'Magic Damage %',
  // PercentMovementSpeedMod: 'Movement Speed %',
  // PercentPhysicalDamageMod: 'Physical Damage %',
  // PercentSpellBlockMod: 'Magic Resist %',
  // PercentSpellVampMod: 'Spell Vamp %',

  // rFlatArmorPenetrationMod: 'Armor Penetration (Flat)',
  // rFlatArmorPenetrationModPerLevel: 'Armor Penetration per Level (Flat)',
  // rFlatCritChanceMod: 'Critical Chance (Flat)',
  // rFlatCritDamageMod: 'Critical Damage (Flat)',
  // rFlatEnergyRegenMod: 'Energy Regen (Flat)',
  // rFlatEnergyRegenModPerLevel: 'Energy Regen per Level (Flat)',
  // rFlatGoldPer10Mod: 'Gold per 10 Seconds (Flat)',
  // rFlatHPModPerLevel: 'Health per Level (Flat)',
  // rFlatHPRegenMod: 'Health Regen (Flat)',
  // rFlatHPRegenModPerLevel: 'Health Regen per Level (Flat)',
  // rFlatMPModPerLevel: 'Mana per Level (Flat)',
  // rFlatMPRegenMod: 'Mana Regen (Flat)',
  // rFlatMPRegenModPerLevel: 'Mana Regen per Level (Flat)',
  // rFlatMagicPenetrationMod: 'Magic Penetration (Flat)',
  // rFlatMagicPenetrationModPerLevel: 'Magic Penetration per Level (Flat)',
  // rFlatMovementSpeedModPerLevel: 'Movement Speed per Level (Flat)',
  // rFlatPhysicalDamageModPerLevel: 'Physical Damage per Level (Flat)',
  // rFlatSpellBlockModPerLevel: 'Magic Resist per Level (Flat)',
  // rFlatTimeDeadMod: 'Time Dead (Flat)',
  // rPercentArmorPenetrationMod: 'Armor Penetration %',
  // rPercentArmorPenetrationModPerLevel: 'Armor Penetration per Level %',
  // rPercentAttackSpeedModPerLevel: 'Attack Speed per Level %',
  // rPercentCooldownMod: 'Cooldown Reduction %',
  // rPercentCooldownModPerLevel: 'Cooldown Reduction per Level %',
  // rPercentMagicPenetrationMod: 'Magic Penetration %',
  // rPercentMagicPenetrationModPerLevel: 'Magic Penetration per Level %',
  // rPercentMovementSpeedMod: 'Movement Speed %',
  // rPercentMovementSpeedModPerLevel: 'Movement Speed per Level %',
// };

export const statNameMap: Record<string, string> = {
  FlatArmorMod: 'Armor',
  FlatPhysicalDamageMod: 'Attack Damage',
  FlatCritChanceMod: 'Critical Strike Chance',
  FlatHPPoolMod: 'Health',
  FlatMPPoolMod: 'Mana',
  FlatMagicDamageMod: 'Magic Damage',
  FlatMovementSpeedMod: 'Movement Speed',
  FlatSpellBlockMod: 'Magic Resist',
  PercentAttackSpeedMod: 'Attack Speed %',
  PercentLifeStealMod: 'Life Steal %',
  FlatHPRegenMod: 'Health Regeneration',
  PercentMovementSpeedMod : 'Movement Speed %'
};
