export const statNameMap: Record<string, string> = {
  armor: 'Armor',
  attackDamage: 'Attack Damage',
  critChance: 'Critical Strike Chance',
  health: 'Health',
  mana: 'Mana',
  abilityPower: 'Ability Power',
  movementSpeed: 'Movement Speed',
  magicResist: 'Magic Resist',
  attackSpeed: 'Attack Speed %',
  lifeSteal: 'Life Steal %',
  healthRegen: 'Health Regeneration',
  movementSpeedPercent: 'Movement Speed %',  

  block: 'Block',
  critChancePercent: 'Critical Strike Chance %',
  critDamagePercent: 'Critical Strike Damage %',
  critDamage: 'Critical Strike Damage %',
  expBonus: 'Bonus Experience',
  expBonusPercent: 'Bonus Experience %',
  energyRegen: 'Energy Regen',
  energyRegenFlat: 'Energy Regen',
  energyRegenPerLevel: 'Energy Regen per Level',
  healthPercent: 'Health %',
  healthRegenPercent: 'Health Regen %',
  healthRegenPerLevel: 'Health Regen per Level',
  healthRegenFlat: 'Health Regen',
  lethality: 'Lethality',
  lifeStealPercent: 'Life Steal %',
  magicDamagePercent: 'Magic Damage %',
  magicPenetration: 'Magic Penetration',
  magicPenFlat: 'Magic Penetration',
  magicPenPercent: 'Magic Penetration %',
  magicPenPerLevel: 'Magic Penetration per Level',
  magicPenPerLevelPercent: 'Magic Penetration per Level %',
  manaRegen: 'Mana Regen',
  manaRegenFlat: 'Mana Regen',
  manaRegenPerLevel: 'Mana Regen per Level',
  manaPerLevelFlat: 'Mana per Level',
  moveSpeedPercent: 'Movement Speed %',
  moveSpeedPercentFlat: 'Movement Speed %',
  moveSpeedPerLevelFlat: 'Movement Speed per Level',
  moveSpeedPerLevelPercent: 'Movement Speed per Level %',
  physicalDamage: 'Physical Damage',
  physicalDamagePercent: 'Physical Damage %',
  physicalDamagePerLevelFlat: 'Physical Damage per Level',
  spellVamp: 'Spell Vamp',
  spellVampPercent: 'Spell Vamp %',
  timeDead: 'Time Dead',
  timeDeadFlat: 'Time Dead',
  goldPer10: 'Gold per 10 Seconds',
  goldPer10Flat: 'Gold per 10 Seconds',
  armorPercent: 'Armor %',
  attackDamagePercent: 'Attack Damage %',
  blockPercent: 'Block %',
  critChanceFlat: 'Critical Chance',
  critDamageFlat: 'Critical Damage',
  armorPenFlat: 'Armor Penetration',
  armorPenPercent: 'Armor Penetration %',
  armorPenPerLevel: 'Armor Penetration per Level',
  armorPenPerLevelPercent: 'Armor Penetration per Level %',
  attackSpeedPerLevelPercent: 'Attack Speed per Level %',
  cooldownReductionPercent: 'Cooldown Reduction %',
  cooldownReductionPerLevelPercent: 'Cooldown Reduction per Level %',
  percentBaseHealthRegen: 'Base Health Regen %',
  baseManaRegen: 'Base Mana Regen',
  baseHealth: 'Base Health',
  baseMana: 'Base Mana',
};
